# OpenSheetConfig.cmake
# Helper module included by the root CMakeLists.txt

# ─── Compiler feature requirements ───────────────────────────────────────────
function(opensheet_require_cxx20 target)
    target_compile_features(${target} PUBLIC cxx_std_20)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF)
endfunction()

# ─── Common warning flags ─────────────────────────────────────────────────────
function(opensheet_add_warnings target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /wd4100 /wd4127)
    else()
        target_compile_options(${target} PRIVATE
            -Wall -Wextra -Wpedantic
            -Wno-unused-parameter
            -Wno-missing-field-initializers
        )
    endif()
endfunction()

# ─── Version header generator ────────────────────────────────────────────────
function(opensheet_generate_version_header)
    set(VERSION_FILE "${CMAKE_BINARY_DIR}/generated/opensheet_version.h")
    file(WRITE ${VERSION_FILE}
"#pragma once
// Auto-generated by CMake — do not edit manually
#define OPENSHEET_VERSION_MAJOR ${PROJECT_VERSION_MAJOR}
#define OPENSHEET_VERSION_MINOR ${PROJECT_VERSION_MINOR}
#define OPENSHEET_VERSION_PATCH ${PROJECT_VERSION_PATCH}
#define OPENSHEET_VERSION_STR   \"${PROJECT_VERSION}\"
#define OPENSHEET_BUILD_DATE    \"${CMAKE_BUILD_DATE}\"
")
    include_directories(${CMAKE_BINARY_DIR}/generated)
endfunction()

# ─── Install helper ───────────────────────────────────────────────────────────
function(opensheet_install_runtime_files)
    install(DIRECTORY ${CMAKE_SOURCE_DIR}/themes/       DESTINATION themes)
    install(DIRECTORY ${CMAKE_SOURCE_DIR}/localization/ DESTINATION localization)
    install(DIRECTORY ${CMAKE_SOURCE_DIR}/resources/    DESTINATION resources)
    install(DIRECTORY ${CMAKE_SOURCE_DIR}/addons/       DESTINATION addons)
    install(DIRECTORY ${CMAKE_SOURCE_DIR}/config/       DESTINATION config)
endfunction()
